Fix weird runtime error about Bevy asset server
thread 'main' panicked at 'Requested resource bevy_asset::asset_server::AssetServer does not exist in the `World`.
                Did you forget to add it using `app.insert_resource` / `app.init_resource`?
                Resources are also implicitly added via `app.add_event`,
                and can be added by plugins.', /Users/rocyu/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_asset-0.8.1/src/assets.rs:324:43