Modify tetromino repr. and rotation system
By tracking the rotation origin of the current tetromino, rotations are trivial: no other state is needed to determine the final position of each block of the tetromino, including the positions of other blocks.

This system of rotation is also extensible; user-defined pieces will have origins known before the round begins, so rotating user-defined pieces is more or less consistent with rotating the built-in pieces.

At the moment, there's a runtime error that I can't figure out (it doesn't seem relevant, though):

thread 'main' panicked at 'Requested resource bevy_asset::asset_server::AssetServer does not exist in the `World`.
                Did you forget to add it using `app.insert_resource` / `app.init_resource`?
                Resources are also implicitly added via `app.add_event`,
                and can be added by plugins.', [home]/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_asset-0.8.1/src/assets.rs:324:43