Disable .cargo/config by default; update README.md
'cargo run' repeatedly returned the following error message:

error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -Zshare-generics=y --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 1)
  --- stderr
  error: the option `Z` is only accepted on the nightly compiler

Unlike other user's errors with that header, my error was unrelated to sccache. I messed around with only copying some of the files to another directory and calling 'cargo run' there, which worked. I gradually copied most of the files (I thought I had copied all of them, but apparently not!) without the error occurring. Upon returning to the original directory, to my utter confusion, cargo provided the error once again. I then thought to examine .cargo/config and found the culprit:

# NOTE: For maximum performance, build using a nightly compiler
# If you are using rust stable, remove the "-Zshare-generics=y" below.

The program had been expecting a nightly build the entire time! I suppose the final line of the error message should've tipped me off sooner. I've commented out .cargo/config entirely; this may be relaxed in the future. The README.md has been modified to explicitly point this out.
# Please enter the commit message for your changes. Lines starting